% Output: area ratio, C*, thrust coefficient, gamma, gas molecular weight, 
% gas specific heat, gas dynamic viscosity, near-side chamber wall gas temperature
function [AR,C_star,C_F,gamma,MW_g,Cp_g,mu_g,T_cns] = runCEA(Pc,Pe,OF,eth_frac)
    k = 1.129;    % Choose starting exit gamma
    gamma(3) = 0; % CEA exit gamma
    
    % Loop until under error threshold (converge on gamma)
    while(abs(k-gamma(3)) > 0.00009)
        % Initial loop condition
        if(gamma(3) == 0) 
            gamma(3) = k;
        end
        
        k = k - 0.94*(k-gamma(3)); % Error correction
    
        % Area ratio Ae/At calculation
        mach_e = sqrt(2/(k-1)*(((Pc/Pe)^((k-1)/k)-1)));
        AR = (((k+1)/2)^(-(k+1)/(2*(k-1))))*((1+((k-1)*(mach_e^2)/2))^((k+1)/(2*(k-1))))/mach_e;
        
        % CEA reactant parameters
        reactants = [CEA.Reactant('C2H5OH(L)',                 ...
                                  'Type','Fuel',               ...
                                  'E',DimVar(-100000,'J/mol'), ...
                                  'T',DimVar(300,'K'),         ...         
                                  'Q',DimVar(eth_frac,'kg'))   ...
                     CEA.Reactant('H2O(L)',                    ...
                                  'Type','Fuel',               ...
                                  'E',DimVar(-100000,'J/mol'), ...
                                  'T',DimVar(300,'K'),         ...         
                                  'Q',DimVar(1-eth_frac,'kg')) ...
                     CEA.Reactant('O2(L)',                     ...
                                  'Type','ox',                 ...
                                  'T',DimVar(90.17,'K'),       ...         
                                  'Q',DimVar(1,'kg'))];        
        
        % Run CEA
        data = CEA.Run(reactants,              ...
                       'ProblemType','Rocket', ...
                       'Flow','eq',            ...
                       'Pc',DimVar(Pc,'psi'),  ...
                       'O/F',OF,               ...
                       'supar', AR,            ...
                       'Outputs',{'t','isp','cp','mw','gamma','cf','vis','cond'});
    
        % Data output
        C_star = data.isp(3).Value * 9.80665 / data.cf(3);
        C_F = [data.cf(1),data.cf(2),data.cf(3)];
        gamma = [data.gamma(1),data.gamma(2),data.gamma(3)];
        MW_g = [data.MolarMass(1).Value,data.MolarMass(2).Value,data.MolarMass(3).Value];
        Cp_g = [data.cp(1).Value,data.cp(2).Value,data.cp(3).Value];
        mu_g = [data.vis(1),data.vis(2),data.vis(3)];
        T_cns = [data.Temperature(1).Value,data.Temperature(2).Value,data.Temperature(3).Value];  
    end
end